# Generated by Django 2.2.2 on 2019-06-21 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=256)),
                ('duration', models.DurationField()),
                ('medical_institutions', models.ManyToManyField(to='remote_registration.MedicalInstitution')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(null=True)),
                ('end', models.TimeField(null=True)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_registration.WeekDays')),
                ('medical_institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_registration.MedicalInstitution')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.Procedure')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.ProcedureCategories')),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.ProcedureCategories'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='medical_institutions',
            field=models.ManyToManyField(through='remote_registration.TimeTable', to='remote_registration.MedicalInstitution'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='procedures',
            field=models.ManyToManyField(to='remote_registration.Procedure'),
        ),
        migrations.AddField(
            model_name='medicalinstitution',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='remote_registration.Provinces'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.MedicalInstitution')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.Personnel')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.Procedure')),
            ],
        ),
    ]
