# Generated by Django 2.2.2 on 2019-06-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('details', models.CharField(max_length=256)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.WeekDays')),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.MedicalInstitution')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.Personnel')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='medical_institutions',
            field=models.ManyToManyField(through='remote_registration.TimeTable', to='remote_registration.MedicalInstitution'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='service',
            field=models.ManyToManyField(to='remote_registration.Procedure'),
        ),
        migrations.AddField(
            model_name='medicalinstitution',
            name='services',
            field=models.ManyToManyField(to='remote_registration.Procedure'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.MedicalInstitution')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.Personnel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_registration.Procedure')),
            ],
        ),
    ]
