# Generated by Django 2.2.2 on 2019-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinstitution',
            name='procedures',
        ),
        migrations.AddField(
            model_name='procedure',
            name='medical_institutions',
            field=models.ManyToManyField(to='remote_registration.MedicalInstitution'),
        ),
    ]
