# Generated by Django 2.2.2 on 2019-06-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_registration', '0002_auto_20190618_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinstitution',
            name='ward',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
