# Generated by Django 2.2.2 on 2019-06-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_registration', '0003_medicalinstitution_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_registration.WeekDays'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='medical_institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_registration.MedicalInstitution'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start',
            field=models.TimeField(null=True),
        ),
    ]
