# Generated by Django 2.2.2 on 2019-06-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_registration', '0005_provinces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinstitution',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='remote_registration.Provinces'),
        ),
    ]
