# Generated by Django 2.2.2 on 2019-06-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_registration', '0006_auto_20190621_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinstitution',
            name='province',
            field=models.CharField(max_length=64),
        ),
    ]
